# Dependabot configuration file
# See: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates

version: 2
updates:
  # PHP (Composer) dependencies
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    target-branch: "develop"
    labels:
      - "dependencies"
      - "php"
    assignees:
      - "tech-lead"
    reviewers:
      - "security-team"
    commit-message:
      prefix: "composer"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # JavaScript (npm) dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    target-branch: "develop"
    labels:
      - "dependencies"
      - "javascript"
    assignees:
      - "frontend-lead"
    reviewers:
      - "security-team"
    commit-message:
      prefix: "npm"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    target-branch: "develop"
    labels:
      - "dependencies"
      - "docker"
    assignees:
      - "devops-lead"
    reviewers:
      - "security-team"
    commit-message:
      prefix: "docker"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    target-branch: "develop"
    labels:
      - "dependencies"
      - "ci-cd"
    assignees:
      - "devops-lead"
    reviewers:
      - "security-team"
    commit-message:
      prefix: "ci"
      include: "scope"

# Global settings
registries:
  composer:
    type: composer-repository
    url: https://packagist.org
    username: "${{secrets.COMPOSER_USERNAME}}"
    password: "${{secrets.COMPOSER_PASSWORD}}"
  
  npm:
    type: npm-registry
    url: https://registry.npmjs.org
    username: "${{secrets.NPM_USERNAME}}"
    password: "${{secrets.NPM_PASSWORD}}"

# Version update strategies
version-strategy:
  auto:
    # Only update to stable versions
    only-stable: true
    # Update to the latest version that matches the version requirement
    update-type: "semver:patch"
